config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/gallery', to: 'static_pages#gallery'
  resources :projects
  get '/project-gallery', to: 'projects#index', as: 'project-gallery'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  self.per_page = 10

  def projects
		projects = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
  end
	# @projects = Project.paginate(:page => params[:page], :per_page => 10, :total_entries => 30)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		# @projects = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    @projects = (1..53)
 	end
end

  # Paginates a static array (extracting a subset of it). The result is a
  # WillPaginate::Collection instance, which is an array with a few more
  # properties about its paginated state.
  #
  # Parameters:
  # * <tt>:page</tt> - current page, defaults to 1
  # * <tt>:per_page</tt> - limit of items per page, defaults to 30
  # * <tt>:total_entries</tt> - total number of items in the array, defaults to
  #   <tt>array.length</tt> (obviously)
  #
  # Example:
  #   arr = ['a', 'b', 'c', 'd', 'e']
  #   paged = arr.paginate(:per_page => 2)      #->  ['a', 'b']
  #   paged.total_entries                       #->  5
  #   arr.paginate(:page => 2, :per_page => 2)  #->  ['c', 'd']
  #   arr.paginate(:page => 3, :per_page => 2)  #->  ['e']
  #
  # This method was originally {suggested by Desi
  # McAdam}[http://www.desimcadam.com/archives/8] and later proved to be the
  # most useful method of will_paginate library.
#   def paginate(options = {})
#     page     = options[:page] || 1
#     per_page = options[:per_page] || WillPaginate.per_page
#     total    = options[:total_entries] || self.length

#     WillPaginate::Collection.create(page, per_page, total) do |pager|
#       pager.replace self[pager.offset, pager.per_page].to_a
#     end
#   end
# end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def gallery
  	@projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
 	<p class="copy">©<%= Time.now.year %> Associate Painting. All rights reserved.</p>
 	<p class="design"> Designed by <%=link_to('High Seas Design House', 'http://hsdesignhouse.com', target: '_blank') %>.</p>
  <a href="#" class="scroll-up">Scroll</a>
</footer>

app/views/layouts/_header.html.erb
<header class="custom">
	<div class="header-box">
	  <div class="logo-block"><%= link_to(image_tag( 'ap-logo.png', alt: 'Associate Painting - Logo', class: 'img-responsive logo'), root_path ) %></div>

		<div class="hcontent">
				<nav>
					<ul>
						<li class="menu-item"><%= link_to "Home", root_path %></li>
						<li class="menu-item"><%= link_to "Project Gallery", project_gallery_path %></li>
					</ul>
				</nav>

				<div class="contact-info">
					<h4 class="phone"><%= number_to_phone(2515047175, delimiter: '-') %></h4>
					<h4 class="email"><%= mail_to('joedfranco@yahoo.com') %></h4>
				</div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= favicon_link_tag 'favicon.png' %>

    <meta name="description" content= "<%= @page_description %>">
    <title><%= @page_title  %> | Associate Painting</title>

      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <% unless current_page?(project_gallery_path) or current_page?(gallery_path) %> <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <% end %>
      <%= render 'layouts/shim' %>

  </head>

	<body class=" <%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
      <div class="main-wrap">
  			<% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>

      	<%= yield %>
      </div>
    <%= render 'layouts/footer' %>
    <% if current_page?(project_gallery_path) or current_page?(gallery_path) %> <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <% end %>
  </body>
</html>

app/views/projects/index.html.erb
<% @page_title = "Project Gallery" %>
<% @page_description = "New Subject" %>

	<section class="head-pg">
		<div class="over"></div>
	</section>




<section class="project-gallery">
<div class="head-box">
		<div class="content">
			<h1>Check Out Some of Our Work</h1>
			<h4>Contact Us Today for a Quote!</h4>
		</div>
	</div>
	<% tag = 0 %>

	<% @projects.each do |project| %>
	  <% tag +=1 %>
		<% link = "https://s3.amazonaws.com/assoc-painting/ap-gallery"+"#{tag}"+".jpg" %>
		<%= link_to(image_tag("#{link}", class: 'img-responsive gall', alt: 'Associate Painting Project Gallery'), image_path("#{link}"), data: { lightbox: "example-set"}) %>
	<% end %>

	</div>
</section>

app/views/static_pages/gallery.html.erb
<% @page_title = "Project Gallery" %>
<% @page_description = "Associate Painting offers Residential, Commercial, Custom, and New Construction painting services. Check out some of our past projects." %>


<div class="clearfix"></div>

<section class="project-gallery">
	<div>



		<section class="project-gallery" style="background-color: #ececec;">
			<% @projects.each do |project| %>
				<% $i = 0 %>
				<% $max = 53 %>
				<% while $i < $max  do %>
					<% tag = $i +=1 %>

					<% link = "https://s3.amazonaws.com/assoc-painting/ap-gallery"+"#{tag}"+".jpg" %>
					<%= link_to(image_tag("#{link}", class: 'img-responsive gall', alt: 'Associate Painting Project Gallery'), image_path("#{link}"), data: { lightbox: "example-set"}) %>
				<% end %>
			<% end %>

			</div>
		</section>



	</div>

</section>

app/views/static_pages/home.html.erb
<% @page_title = "Associate Painting | Gulf Shores, Al" %>
<% @page_description = "Associate Painting offers Residential, Commercial, Custom, and New Construction painting services. Delivering quality workmanship along the Gulf Coast since 1995." %>

<section class="home-header">
	<div class="overlay">
		<!-- <div class="container"> -->
			<div class="text-box">
				<h1><%=image_tag('logo-text.png', alt: 'Associate Painting, serving the Gulf Coast', class: 'h1-img') %></h1>
				<div class="title-line"></div>
				<div class="clearfix"></div>
					<h3>Serving the Gulf Coast since 1995</h3>
					<h3 class="quote">Call Us Today for a Quote</h3>
			</div>
		<!-- </div> -->
	</div>
</section>
<section class="home-sec1">
	<div class="home-banner">
		<div class="content">
			<div class="inner">
				<%= image_tag('roller-clear.png', class: 'icon', alt: '') %>
				<div class="text">
					<h3>Quality Guaranteed</h3>
					<p>From the products we use, to the results we deliver, Associate Painting has you covered!</p>
				</div>
			</div>
		</div>
	</div>

	<div class="container no-padding">
		<div class="inside">
			<div class="title-blk">

				<h4><span>See What Makes Associate Painting</span><br> Baldwin County's Top Painting Service</h4>
				<p>Associate Painting has been providing professional, dependable workmanship along the Gulf Coast for more than 20 years. Our team incorporates an unbeatable blend of skill, experience, and efficiency into every project.</p>

				<p>We offer a variety of residential and commercial services throughout Baldwin County. Contact us today for more information, or to discuss what Associate Painting can do for you!</p>
				<div class="service-arr">
					Our Services Include
					<i class="fa fa-angle-double-right full"></i>
					<i class="fa fa-angle-double-down xs"></i>
				</div>
			</div>

			<div class="service-blocks">
				<div class="top">
					<div class="service-blk res">
						<div class="over">
							<h3>Residential<br>
							<span>Paint Jobs</span></h3>
						</div>
					</div>

					<div class="service-blk com">
						<div class="over">
							<h3>Commercial<br>
							<span>Paint Jobs</span></h3>
						</div>
					</div>
				</div>

				<div class="bottom">
					<div class="service-blk new">
						<div class="over">
							<h3>New Construction<br>
							<span>Paint Jobs</span></h3>
						</div>
					</div>

					<div class="service-blk cus">
						<div class="over">
							<h3>Custom <br>
							<span>Paint Jobs</span></h3>
						</div>
					</div>
				</div>


			</div>
		</div>
	</div>
</section>

<section class="home-sec2">
	<div class="container">
		<div class="content">
			<h3>Trust Associate Painting<br>
				<span>to do the job right!</span>
			</h3>

			<p>Our team can help take the stress out of your home improvements! <br>
			We use the highest quality products, to increase the durability of our work, and the proficiency with which it is done. </p>
		</div>
		<div class="boxes">
			<div class="box-link gall">
				<div class="overlay">
					<h4>Take a look at our</h4>
					<h3><%= link_to("Project Gallery", project_gallery_path) %></h3>
				</div>
			</div>

			<div class="box-link quote">
				<div class="overlay">
					<div class="text">
						<h3>Contact Us Today <br>For a Quote!</h3>
						<h4 class="phone"><%= number_to_phone(2515047175, delimiter: '-', class: 'phone') %></h4>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>